name: Marvellous Minutiae
favicon: null
layout_spectrum: 0.27447420824319124
typography_spectrum: 0.31136015872471035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4772438316140324
  lightness: 0.5816294094547629
  saturation: 0.06185822049155831
  rhythmicContrast: 0.2352559755090624
purpose: []
